fix: Use Yeoman generated Spring Boot app for BFF
ibm-developer/generator-ibm-java-spring pull request #20
Opened 2018-02-13 18:23 UTC by paulben

2018-02-13 18:26 UTC, quanvo87 approved these changes

2018-02-13 18:28 UTC, quanvo87 requested changes
Looks like you will need to remove relevant tests.

2018-02-14 15:32 UTC, quanvo87 commented
Looks like `npm run lint` is now failing. You can also run this command locally to see what is causing this.

2018-02-14 19:39 UTC, quanvo87 approved these changes

2018-02-14 20:25 UTC, merged

2018-02-15 09:08 UTC, MarkNSweep commented
I would consider adding tests that check Swagger2SpringBoot.java is not present rather than just removing the check for that file entirely. It's in the templates so could creep back in at a later date.